### ISSUE TITLE
FFmpeg support available

### ISSUE THREAD

**Issue by NickeManarin** [jvanegmond/screentogif#1]
Hi @jvanegmond, I noticed this project and your changes you did to the code to support FFmpeg (back in 2015).

I'm here just to inform that ScreenToGif has FFmpeg integrated, if you are not aware of it, of course.

https://github.com/NickeManarin/ScreenToGif

:)

**Comment by jvanegmond** [comment]
And you switched the project to GitHub! That's cool.

I tried ffmpeg support out today. It works perfectly. A great addition to an already great piece of software.

For this project I made a change to the readme to now redirect people to your master branch.

Many thanks for providing this great tool.

**Comment by NickeManarin** [comment]
Great :D
Thank you for you kind words.
